version: "3.7"
# Declaração dos serviços.
services:
  # Configuração do container do Postgres.
  pgsql-metabase-docker:
    # Nome da imagem a ser buscada.
    image: postgres
    # Permite escolher reiniciar caso o serviço pare.
    restart: always
    # Especificação do expose das portas.
    ports:
      - 5432:5432
    # Criação das váriaveis de ambiente.
    environment:
      # Senha para o banco.
      POSTGRES_PASSWORD: postgres
      # Usuário
      POSTGRES_USER: metabase
      #Nome do Banco
      POSTGRES_DB: metabase
    # Indicação do diretório para volume.  
    volumes:
      # Use um diretório que já esteja criado.
      - /HOME/docker/volumes/postgres:/var/lib/postgresql/data

